### PR TITLE
chore: exclude index files from being committed + override Gemfiles

### PR DESCRIPTION
**Pull request by stefanomunarini**

### CODE REVIEW

**Review by kesara — CHANGES_REQUESTED** [review]
@stefanomunarini I think this PR should delete the 4 index files in the root directory.

Also, I think it would be better if you remove data directory updates from the PR, and let them update with GHA for clarity.

**Comment by stefano-tech-ai** [comment]
> @stefanomunarini I think this PR should delete the 4 index files in the root directory.
> 
> Also, I think it would be better if you remove data directory updates from the PR, and let them update with GHA for clarity.

That's right. I've updated the PR, now ready for final review

**Comment by kesara** [comment]
> > @stefanomunarini I think this PR should delete the 4 index files in the root directory.
> > Also, I think it would be better if you remove data directory updates from the PR, and let them update with GHA for clarity.
> 
> That's right. I've updated the PR, now ready for final review

You will have to remove the following commit from the PR: 3dd92844b7bca054c7296a85a2bc19624537d663

**Comment by stefano-tech-ai** [comment]
@kesara here is the update to the workflow, whereas in #13 is the removal of indexes

**Review by kesara — APPROVED** [review]

**Pull request merged**
